# Change these first
owner: maxneuvians # Your GitHub organization or username, where this repository lives
repo: status-statut # The name of this repository

sites:
  - name: Canada.ca
    url: https://www.canada.ca/
  - name: Page d'accueil de Condition féminine Canada / Status of Women Canada Web Welcome Page
    url: https://cfc-swc.gc.ca/
  - name: Canadian Institutes of Health Research / Instituts de recherche en santé du Canada
    url: https://cihr-irsc.gc.ca/
  - name: Conseil de la radiodiffusion et des télécommunications canadiennes / Canadian Radio-television and Telecommunications Commission / CRTC
    url: https://crtc.gc.ca/
  - name: Canadian Museum for Human Rights
    url: https://humanrights.ca/
  - name: Home / Ingenium
    url: https://ingeniumcanada.org/
  - name: Immigration and Refugee Board of Canada
    url: https://irb-cisr.gc.ca/
  - name: Bibliothèque et Archives Canada / Library and Archives Canada
    url: https://library-archives.canada.ca/
  - name: Language selection - Military Police Complaints Commission of Canada / Sélection de la langue - Commission d’examen des plaintes concernant la police militaire du Canada
    url: https://www.mpcc-cppm.gc.ca/
  - name: National Arts Centre / Canada is our stage
    url: https://nac-cna.ca/
  - name: Canadian Museum of Nature
    url: https://nature.ca/
  - name: National Capital Commission -  National Capital Commission
    url: https://ncc-ccn.gc.ca
  - name: Language selection - Northern Pipeline Agency / Sélection de la langue - Administration du pipe-line du Nord
    url: https://northern-pipeline.canada.ca
  - name: Home - National Research Council Canada
    url: https://nrc.canada.ca/en/
  - name: Canadian Transportation Agency
    url: https://otc-cta.gc.ca/
  - name: Prime Minister of Canada / Premier ministre du Canada
    url: https://pm.gc.ca
  - name: Travel.gc.ca - Home
    url: https://travel.gc.ca/
  - name: Weather Information - Environment Canada
    url: https://weather.gc.ca/
  - name: Agence de promotion économique du Canada atlantique / Atlantic Canada Opportunities Agency
    url: https://www.acoa-apeca.gc.ca/
  - name: Atomic Energy of Canada Ltd (AECL) - Home
    url: https://www.aecl.ca/
  - name: Language selection - Agriculture and Agri-Food Canada / Sélection de la langue - Agriculture et Agroalimentaire Canada
    url: https://www.agr.gc.ca/
  - name: Agence spatiale canadienne / Canadian Space Agency
    url: https://www.asc-csa.gc.ca/
  - name: Bank of Canada
    url: https://www.bankofcanada.ca/
  - name: BDC - The Bank for Canadian Entrepreneurs / BDC.ca
    url: https://www.bdc.ca/
  - name: Mailing and shipping for Personal and Business / Canada Post
    url: https://www.canadapost-postescanada.ca/
  - name: Canadian Northern Economic Development Agency / Agence canadienne de développement économique du Nord - Canada.ca
    url: https://www.cannor.gc.ca/
  - name: Welcome to Courts Administration Service / Bienvenue au Service administratif des tribunaux judiciaires
    url: https://www.cas-satj.gc.ca/
  - name: Canadian Air Transport Security Authority / L'administration canadienne de la sûreté du transport aérien
    url: https://www.catsa-acsta.gc.ca/
  - name: CBC.ca - watch, listen, and discover with Canada's Public Broadcaster
    url: https://www.cbc.ca/
  - name: Copyright Board of Canada
    url: https://www.cb-cda.gc.ca/
  - name: Canada Border Services Agency / Agence des services frontaliers du Canada
    url: https://www.cbsa-asfc.gc.ca/
  - name: Bienvenue sur les plaines d'Abraham / Welcome to the Plains of Abraham
    url: https://www.ccbn-nbc.gc.ca/
  - name: Canadian Commercial Corporation / CCC
    url: https://www.ccc.ca/
  - name: Canadian Centre for Occupational Health and Safety
    url: https://www.ccohs.ca/
  - name: Canada Deposit Insurance Corporation / Société d'assurance-dépôts du Canada
    url: https://www.cdic.ca/
  - name: Canada Energy Regulator Site / Site de Régie de l’énergie du Canada
    url: https://www.cer-rec.gc.ca/
  - name: Home / Canadian Human Rights Commission
    url: https://www.chrc-ccdp.gc.ca/
  - name: Canada Mortgage and Housing Corporation
    url: https://www.cmhc-schl.gc.ca/
  - name: Canadian Nuclear Safety Commission - Commission canadienne de sûreté nucléaire
    url: https://www.cnsc-ccsn.gc.ca/
  - name: Welcome / Civilian Review and Complaints Commission for the RCMP
    url: https://www.crcc-ccetp.gc.ca/
  - name: Correctional Service Canada / Service correctionnel Canada
    url: https://www.csc-scc.gc.ca/
  - name: Communications Security Establishment
    url: https://www.cse-cst.gc.ca/
  - name: Canada School of Public Service / École de la fonction publique du Canada
    url: https://www.csps-efpc.gc.ca/
  - name: DEC / Développement économique Canada pour les régions du Québec / Accueil
    url: https://www.dec-ced.gc.ca/
  - name: Fisheries and Oceans Canada / Pêches et Océans Canada
    url: https://www.dfo-mpo.gc.ca/
  - name: Export Development Canada (EDC)
    url: https://www.edc.ca/
  - name: Farm Credit Canada / FCC
    url: https://www.fcc-fac.ca/
  - name: Federal Economic Development Agency for Southern Ontario Main Site / Site principal Agence fédérale de développement économique pour le Sud de l'Ontario
    url: https://www.feddevontario.gc.ca/
  - name: Financial Transactions and Reports Analysis Centre of Canada (FINTRAC) / Centre d'analyse des opérations et déclarations financières du Canada (CANAFE)
    url: https://www.fintrac-canafe.gc.ca/
  - name: Office of the Commissioner for Federal Judicial Affairs Canada
    url: https://www.fja-cmf.gc.ca/
  - name: National Gallery of Canada
    url: https://www.gallery.ca/
  - name: Governor General of Canada / Gouverneure générale du Canada
    url: https://www.gg.ca/
  - name: Canadian Grain Commission (CGC) / Commission canadienne des grains (CCG)
    url: https://www.grainscanada.gc.ca/
  - name: Home / Canadian Museum of History
    url: https://www.historymuseum.ca/
  - name: Innovation, Science and Economic Development Canada Main Site /  Site principal d'Innovation, Sciences et Développement économique Canada
    url: https://www.ic.gc.ca/
  - name: IDRC - International Development Research Centre
    url: https://www.idrc.ca/
  - name: Infrastructure Canada / Infrastructure Canada
    url: https://www.infrastructure.gc.ca/
  - name: Canadian Food Inspection Agency / Agence canadienne d'inspection des aliments
    url: https://www.inspection.gc.ca/
  - name: Global Affairs Canada – Splash page / Affaires mondiales Canada – Page de garde
    url: https://www.international.gc.ca/
  - name: Department of Justice / Ministère de la Justice
    url: https://www.justice.gc.ca/
  - name: Canadian Coins, Gold, Silver & More  / The Royal Canadian Mint
    url: https://www.mint.ca/
  - name: National Film Board of Canada
    url: https://www.nfb.ca/
  - name: Natural Resources Canada / Ressources naturelles Canada
    url: https://www.nrcan.gc.ca/
  - name: Natural Sciences and Engineering Research Council of Canada  / Conseil de recherches en sciences naturelles et en génie du Canada
    url: https://www.nserc-crsng.gc.ca/
  - name: National Security and Intelligence Committee of Parliamentarians (NSICOP)
    url: https://www.nsicop-cpsnr.ca/
  - name: Office of the Correctional Investigator / Bureau de l'enquêteur correctionnel
    url: https://www.oci-bec.gc.ca/
  - name: Office of the Superintendent of Financial Institutions
    url: https://www.osfi-bsif.gc.ca/
  - name: Parks Canada
    url: https://www.pc.gc.ca/
  - name: Public Prosecution Service of Canada / Service des poursuites pénales du Canada
    url: https://www.ppsc-sppc.gc.ca/
  - name: Public Safety Canada / Sécurité publique Canada
    url: https://www.publicsafety.gc.ca/
  - name: Relations Couronne-Autochtones et Affaires du Nord Canada / Crown-Indigenous Relations and Northern Affairs Canada - Canada.ca
    url: https://www.rcaanc-cirnac.gc.ca/
  - name: National Home Page / Royal Canadian Mounted Police
    url: https://www.rcmp-grc.gc.ca/
  - name: Services aux Autochtones Canada / Indigenous Services Canada - Canada.ca
    url: https://www.sac-isc.gc.ca/
  - name: Supreme Court of Canada / Cour suprême du Canada
    url: https://www.scc-csc.ca/
  - name: Canadian Intergovernmental Conference Secretariat / SecrÕtariat des confÕrences intergouvernementales canadiennes
    url: https://www.scics.ca/
  - name: Social Sciences and Humanities Research Council / Conseil de recherches en sciences humaines
    url: https://www.sshrc-crsh.gc.ca/
  - name: Statistics Canada - Canada's national statistical agency / Statistique Canada - Organisme statistique national du Canada
    url: https://www.statcan.gc.ca/
  - name: Transport Canada / Transports Canada
    url: https://www.tc.gc.ca/
  - name: Transportation Safety Board of Canada / Bureau de la sécurité des transports du Canada
    url: https://www.tsb.gc.ca/
  - name: Welcome to the Treasury Board of Canada Secretariat / Bienvenue au Secrétariat du Conseil du Trésor du Canada
    url: https://www.tbs-sct.gc.ca/
  - name: Veterans Affairs Canada / Anciens Combattants Canada
    url: https://www.veterans.gc.ca/
  - name: Veterans Review and Appeal Board / Tribunal des anciens combattants (révision et appel)
    url: https://www.vrab-tacra.gc.ca/
  - name: Western Economic Diversification Canada / Diversification de l'économie de l'Ouest Canada
    url: https://www.wd-deo.gc.ca/
  - name: Canada Border Services Agency / Agence des services frontaliers du Canada
    url: http://www.cbsa-asfc.gc.ca/
  - name: Global Affairs Canada / Affaires mondiales Canada
    url: http://www.international.gc.ca/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: neuvians.io
  baseUrl: /status-statut
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ""
  introTitle: "Government of Canada / Gouvernement du Canada"
  introMessage: Status page for the Government of Canada / Page de statut pour le  Gouvernement du Canada
  navbar:
    - title: Status / Statut
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  activeIncidents: Active Incidents / Incidents actifs
  allSystemsOperational: All systems are operational / Tous les systèmes sont opérationnels
  incidentReport: "Incident #$NUMBER report / Rapport d'incident #$NUMBER →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts / Ouvert à $DATE avec des postes $POSTS
  incidentTitle: Incident $NUMBER Details / Détails de l'incident $NUMBER
  incidentDetails: Incident Details / Détails de l'incident
  incidentFixed: Fixed / Fixé
  incidentOngoing: Ongoing / En cours
  incidentOpenedAt: Opened at / Ouvert à
  incidentClosedAt: Closed at / Fermé à
  incidentViewOnGitHub: View and Subscribe on GitHub / Voir et s'abonner sur GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR / Posté à $DATE par $AUTHOR
  incidentBack: ← Back to all incidents / Retour à tous les incidents
  pastIncidents: Past Incidents / Incidents passés
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts / Résolu en $MINUTES minutes avec les messages $POSTS
  liveStatus: Live Status / Statut en direct
  overallUptime: "Overall uptime / Temps de fonctionnement global: $UPTIME"
  overallUptimeTitle: Overall uptime / Temps de fonctionnement global
  averageResponseTime: "Average response time / Temps de réponse moyen : $TIMEms"
  averageResponseTimeTitle: Average response / Réponse moyenne
  sevelDayResponseTime: 7-day response time / Délai de réponse de 7 jours
  responseTimeMs: Response time (ms) / Temps de réponse (ms)
  up: Up / Opérationnel
  down: Down / En panne
  degraded: Degraded / Détérioré
  loading: Loading / Chargement
  footer: Government of Canada / Gouvernement du Canada
  pastScheduledMaintenance: Past Scheduled Maintenance / Maintenance programmée passée
  scheduledMaintenance: Scheduled Maintenance / Maintenance programmée
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes / Démarré à $DATE pour $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes / Commence à $DATE pour $DURATION minutes
  startedAt: Started at / Commencé à
  startsAt: Starts at / Commence à
  duration: Duration / Durée
  durationMin: $DURATION minutes
  incidentCompleted: Completed / Complété
  incidentScheduled: Scheduled / Programmé
